[build-system]
requires = ["setuptools>=61.2"]
build-backend = "setuptools.build_meta"

[project]
name = "subpackage"
version = "0.1.0"

[project.optional-dependencies]
test = ["pytest"]

[dependency-groups]
test = ["pytest>=8.0.0"]

[tool.setuptools]
include-package-data = false

[tool.setuptools.packages]
find = {namespaces = false}
