on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/publish_pure_python.yml
      - .github/workflows/test_publish_pure_python.yml
  pull_request:
    paths:
      - .github/workflows/publish_pure_python.yml
      - .github/workflows/test_publish_pure_python.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    uses: ./.github/workflows/publish_pure_python.yml
    with:
      test_groups: test, concurrency
      test_extras: recommended
      test_command: pytest --pyargs test_package
      timeout-minutes: 5

  publish_testpypi:
    if: ${{ secrets.test_pypi_token != '' }}
    uses: ./.github/workflows/publish_pure_python.yml
    with:
      upload_to_pypi: true
      repository_url: https://test.pypi.org/legacy/
      timeout-minutes: 5
    secrets:
      pypi_token: ${{ secrets.test_pypi_token }}

  setenv:
    uses: ./.github/workflows/publish_pure_python.yml
    with:
      test_command: python -c "import os; assert os.getenv('CUSTOM_VAR') == 'custom value'"
      env: |
        CUSTOM_VAR: custom value
