on: [push]

jobs:
  release:
    uses: ./publish.yml@main
    with:
      pure_python_wheel: true
      test_extras: test
      test_command: pytest --pyargs test_package
  release_with_cibuildwheel:
    uses: ./publish.yml@main
    with:
      pure_python_wheel: false
      test_extras: test
      test_command: pytest --pyargs test_package
