on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/publish_pure_python.yml
      - .github/workflows/test_publish_pure_python.yml
  pull_request:
    paths:
      - .github/workflows/publish_pure_python.yml
      - .github/workflows/test_publish_pure_python.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    uses: ./.github/workflows/publish_pure_python.yml
    with:
      test_groups: test, concurrency
      test_extras: recommended
      test_command: pytest --pyargs test_package
      timeout-minutes: 5

  setenv:
    uses: ./.github/workflows/publish_pure_python.yml
    with:
      save_artifact: true
      test_command: python -c "import os; assert os.getenv('CUSTOM_VAR') == 'custom value'"
      env: |
        CUSTOM_VAR: custom value


  test-upload-external:
    name: Use built dists and test upload
    runs-on: ubuntu-latest
    needs: [setenv]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v5
        with:
          merge-multiple: true
          pattern: dist-*
          path: dist

      - run: ls -lha dist/

      - name: Run upload (but don't actually upload)
        uses: pypa/gh-action-pypi-publish@release/v1
